version: '2.0'
services:
  mysql:
    image: mysql:5.7
    user: '1000:50'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_USER: codemed
      MYSQL_PASSWORD: '123'
    volumes:
      - ./data:/var/lib/mysql
    command: "--disable-partition-engine-check=false"
    command: "--innodb_use_native_aio=0"
  web:
    depends_on:
      - mysql
    image: 'centos-php'
    command: ["httpd", "-D", "FOREGROUND"]
    command: "php artisan serve --host=0.0.0.0 --port 8000"
    ports:
      - '80:80'
      - '8000:8000'
    volumes:
      - .:/var/www/html
      - ./vhost:/etc/apache2/sites-enabled